MOSAIC RTC Core: mosaic::core_signaling::SignalingClient Class Reference
mosaic::core_signaling::SignalingClient Class Reference
#include <signaling_client.h>
Public Member Functions
SignalingClient (const std::string &ws_uri)
~SignalingClient () override
void Start () override
void Stop () override
void SendSdpAnswer (const webrtc::SessionDescriptionInterface *sdp) const override
void SendIceCandidate (const webrtc::IceCandidateInterface *candidate) const override
void SendState (const int state) const override
void SetMosaicConnector (const std::shared_ptr< core::MosaicConnector > &mosaic_connector) override
void SetAuthenticator (const std::shared_ptr< security::IMosaicAuthenticator > &authenticator) override
bool IsAuthenticated () const override
void SendWsMessage (const Json::Value &message) const override
Public Member Functions inherited from mosaic::core_signaling::ISignalingClient
virtual ~ISignalingClient ()=default
Private Member Functions
void OnWsMessage (const std::string &msg) const
void OnMessage (Json::Value const &message) const
void HandleSendSdpOffer (Json::Value const &message) const
void HandleExchangeIceCandidate (Json::Value const &message) const
void HandleCloseConnection () const
void HandleAuthorizationMessage (const std::string &type, Json::Value const &message) const
void StartInternal ()
Private Attributes
std::shared_ptr< core::MosaicConnector > mosaic_connector_
std::shared_ptr< security::IMosaicAuthenticator > authenticator_
bool is_connected_ = false
std::string ws_uri_
std::unique_ptr< WebSocketClient > ws_client_ = nullptr
int latest_state_ = -1
std::string current_rtc_connection_id_
Detailed Description
Definition at line 16 of file signaling_client.h.
Constructor & Destructor Documentation
SignalingClient()
SignalingClient::SignalingClient (const std::string & ws_uri) explicit
Definition at line 16 of file signaling_client.cpp.
~SignalingClient()
SignalingClient::~SignalingClient () override
Definition at line 18 of file signaling_client.cpp.
References Stop().
Member Function Documentation
HandleAuthorizationMessage()
void SignalingClient::HandleAuthorizationMessage (const std::string & type, Json::Value const & message) const private
Definition at line 201 of file signaling_client.cpp.
References authenticator_.
Referenced by OnMessage().
HandleCloseConnection()
void SignalingClient::HandleCloseConnection () const private
Definition at line 197 of file signaling_client.cpp.
References mosaic_connector_.
Referenced by OnMessage().
HandleExchangeIceCandidate()
void SignalingClient::HandleExchangeIceCandidate (Json::Value const & message) const private
Definition at line 185 of file signaling_client.cpp.
References mosaic_connector_, MOSAIC_LOG_WARNING, and ResolveIceCandidate().
Referenced by OnMessage().
HandleSendSdpOffer()
void SignalingClient::HandleSendSdpOffer (Json::Value const & message) const private
Definition at line 174 of file signaling_client.cpp.
References mosaic_connector_, MOSAIC_LOG_WARNING, and ResolveSdpOffer().
Referenced by OnMessage().
IsAuthenticated()
bool SignalingClient::IsAuthenticated () const override virtual
Implements mosaic::core_signaling::ISignalingClient.
Definition at line 96 of file signaling_client.cpp.
References authenticator_.
OnMessage()
void SignalingClient::OnMessage (Json::Value const & message) const private
Definition at line 150 of file signaling_client.cpp.
References HandleAuthorizationMessage(), HandleCloseConnection(), HandleExchangeIceCandidate(), HandleSendSdpOffer(), and MOSAIC_LOG_DEBUG.
Referenced by OnWsMessage().
OnWsMessage()
void SignalingClient::OnWsMessage (const std::string & msg) const private
Definition at line 133 of file signaling_client.cpp.
References MOSAIC_LOG_ERROR, and OnMessage().
Referenced by StartInternal().
SendIceCandidate()
void SignalingClient::SendIceCandidate (const webrtc::IceCandidateInterface * candidate) const override virtual
Implements mosaic::core_signaling::ISignalingClient.
Definition at line 50 of file signaling_client.cpp.
References current_rtc_connection_id_, is_connected_, and SendWsMessage().
SendSdpAnswer()
void SignalingClient::SendSdpAnswer (const webrtc::SessionDescriptionInterface * sdp) const override virtual
Implements mosaic::core_signaling::ISignalingClient.
Definition at line 33 of file signaling_client.cpp.
References current_rtc_connection_id_, is_connected_, and SendWsMessage().
SendState()
void SignalingClient::SendState (const int state) const override virtual
Implements mosaic::core_signaling::ISignalingClient.
Definition at line 73 of file signaling_client.cpp.
References is_connected_, latest_state_, and SendWsMessage().
Referenced by StartInternal().
SendWsMessage()
void SignalingClient::SendWsMessage (const Json::Value & message) const override virtual
Implements mosaic::core_signaling::ISignalingClient.
Definition at line 168 of file signaling_client.cpp.
References ws_client_.
Referenced by SendIceCandidate(), SendSdpAnswer(), and SendState().
SetAuthenticator()
void SignalingClient::SetAuthenticator (const std::shared_ptr< security::IMosaicAuthenticator > & authenticator) override virtual
Implements mosaic::core_signaling::ISignalingClient.
Definition at line 92 of file signaling_client.cpp.
References authenticator_.
SetMosaicConnector()
void SignalingClient::SetMosaicConnector (const std::shared_ptr< core::MosaicConnector > & mosaic_connector) override virtual
Implements mosaic::core_signaling::ISignalingClient.
Definition at line 88 of file signaling_client.cpp.
References mosaic_connector_.
Start()
void SignalingClient::Start () override virtual
Implements mosaic::core_signaling::ISignalingClient.
Definition at line 22 of file signaling_client.cpp.
References StartInternal().
StartInternal()
void SignalingClient::StartInternal () private
Definition at line 100 of file signaling_client.cpp.
References is_connected_, latest_state_, MOSAIC_LOG_ERROR, MOSAIC_LOG_INFO, OnWsMessage(), SendState(), ws_client_, and ws_uri_.
Referenced by Start().
Stop()
void SignalingClient::Stop () override virtual
Implements mosaic::core_signaling::ISignalingClient.
Definition at line 26 of file signaling_client.cpp.
References is_connected_, and ws_client_.
Referenced by ~SignalingClient().
Member Data Documentation
authenticator_
std::shared_ptr<security::IMosaicAuthenticator> mosaic::core_signaling::SignalingClient::authenticator_ private
Definition at line 54 of file signaling_client.h.
Referenced by HandleAuthorizationMessage(), IsAuthenticated(), and SetAuthenticator().
current_rtc_connection_id_
std::string mosaic::core_signaling::SignalingClient::current_rtc_connection_id_ private
Definition at line 59 of file signaling_client.h.
Referenced by SendIceCandidate(), and SendSdpAnswer().
is_connected_
bool mosaic::core_signaling::SignalingClient::is_connected_ = false private
Definition at line 55 of file signaling_client.h.
Referenced by SendIceCandidate(), SendSdpAnswer(), SendState(), StartInternal(), and Stop().
latest_state_
int mosaic::core_signaling::SignalingClient::latest_state_ = -1 private
Definition at line 58 of file signaling_client.h.
Referenced by SendState(), and StartInternal().
mosaic_connector_
std::shared_ptr<core::MosaicConnector> mosaic::core_signaling::SignalingClient::mosaic_connector_ private
Definition at line 53 of file signaling_client.h.
Referenced by HandleCloseConnection(), HandleExchangeIceCandidate(), HandleSendSdpOffer(), and SetMosaicConnector().
ws_client_
std::unique_ptr<WebSocketClient> mosaic::core_signaling::SignalingClient::ws_client_ = nullptr private
Definition at line 57 of file signaling_client.h.
Referenced by SendWsMessage(), StartInternal(), and Stop().
ws_uri_
std::string mosaic::core_signaling::SignalingClient::ws_uri_ private
Definition at line 56 of file signaling_client.h.
Referenced by StartInternal().
The documentation for this class was generated from the following files:
include/mosaic/signaling/signaling_client.h
src/signaling/signaling_client.cpp