MOSAIC RTC Core: mosaic::handlers::DataChannelSendable Class Reference
mosaic::handlers::DataChannelSendable Class Reference
#include <data_channel_sendable.h>
Public Member Functions
DataChannelSendable (const std::string &label)
~DataChannelSendable () override=default
bool Sendable () const
void Send (const webrtc::DataBuffer &buffer, bool isAsync=false) const
void SendString (const std::string &string, bool isAsync=false) const
void SendStringAsByte (const std::string &string, bool isAsync=false) const
void SendJson (const Json::Value &json_data, bool isAsync=false) const
Public Member Functions inherited from mosaic::handlers::ADataChannelHandler
ADataChannelHandler (const std::string &label)
~ADataChannelHandler () override=default
std::string GetLabel () const override
void OnMessage (const webrtc::DataBuffer &) override
void SetDataChannelInterface (const webrtc::scoped_refptr< webrtc::DataChannelInterface > &dc_interface) const override
void RegisterDataChannelObserver () const override
ChannelState GetState () const override
void CloseDataChannel () const override
Public Member Functions inherited from mosaic::handlers::IDataChannelHandler
IDataChannelHandler ()=default
virtual ~IDataChannelHandler ()=default
virtual void AfterCreate ()
Additional Inherited Members
Public Types inherited from mosaic::handlers::IDataChannelHandler
enum ChannelState {
kConnecting , kOpen , kClosing , kClosed ,
kUnknown
}
Detailed Description
Definition at line 12 of file data_channel_sendable.h.
Constructor & Destructor Documentation
DataChannelSendable()
mosaic::handlers::DataChannelSendable::DataChannelSendable (const std::string & label) inline explicit
Definition at line 14 of file data_channel_sendable.h.
~DataChannelSendable()
mosaic::handlers::DataChannelSendable::~DataChannelSendable () override default
Member Function Documentation
Send()
void DataChannelSendable::Send (const webrtc::DataBuffer & buffer, bool isAsync = false) const
Definition at line 17 of file data_channel_sendable.cpp.
References MOSAIC_LOG_ERROR, mosaic::handlers::ADataChannelHandler::Send(), Sendable(), and mosaic::handlers::ADataChannelHandler::SendAsync().
Referenced by SendJson(), SendString(), and SendStringAsByte().
Sendable()
bool DataChannelSendable::Sendable () const
Definition at line 12 of file data_channel_sendable.cpp.
References mosaic::handlers::ADataChannelHandler::GetState(), and mosaic::handlers::IDataChannelHandler::kOpen.
Referenced by Send(), SendJson(), SendString(), and SendStringAsByte().
SendJson()
void DataChannelSendable::SendJson (const Json::Value & json_data, bool isAsync = false) const
Definition at line 47 of file data_channel_sendable.cpp.
References MOSAIC_LOG_ERROR, Send(), and Sendable().
SendString()
void DataChannelSendable::SendString (const std::string & string, bool isAsync = false) const
Definition at line 29 of file data_channel_sendable.cpp.
References MOSAIC_LOG_ERROR, Send(), and Sendable().
SendStringAsByte()
void DataChannelSendable::SendStringAsByte (const std::string & string, bool isAsync = false) const
Definition at line 38 of file data_channel_sendable.cpp.
References MOSAIC_LOG_ERROR, Send(), and Sendable().
The documentation for this class was generated from the following files:
include/mosaic/handlers/data_channel/data_channel_sendable.h
src/handlers/data_channel/data_channel_sendable.cpp