MOSAIC RTC Core: mosaic::auto_configurer::AutoConfigurer Class Reference
mosaic::auto_configurer::AutoConfigurer Class Reference
#include <auto_configurer.h>
Public Member Functions
AutoConfigurer ()=default
virtual ~AutoConfigurer ()=default
virtual void BeforeConfigure ()
void AutoConfigure (const std::string &config_file_path)
virtual void AfterConfigure ()
std::shared_ptr< core::MosaicConnector > GetMosaicConnector () const
void ReadConfigs (const std::string &config_file_path)
void CreateMosaicConnector ()
void ResolveConnectors ()
void ConfigureConnectors ()
Protected Attributes
std::shared_ptr< core::MosaicConfig > mosaic_config_
std::shared_ptr< core::MosaicConnector > mosaic_connector_
std::vector< std::shared_ptr< IConfigurableConnector > > configurable_connectors_
std::unordered_map< std::string, std::shared_ptr< handlers::IDataChannelHandler > > dc_handler_map_
std::unordered_map< std::string, std::shared_ptr< handlers::IMediaTrackHandler > > mt_handler_map_
Private Attributes
std::shared_ptr< IConfigReader > config_reader_
Detailed Description
Definition at line 16 of file auto_configurer.h.
Constructor & Destructor Documentation
AutoConfigurer()
mosaic::auto_configurer::AutoConfigurer::AutoConfigurer () default
~AutoConfigurer()
virtual mosaic::auto_configurer::AutoConfigurer::~AutoConfigurer () virtual default
Member Function Documentation
AfterConfigure()
virtual void mosaic::auto_configurer::AutoConfigurer::AfterConfigure () inline virtual
Definition at line 26 of file auto_configurer.h.
Referenced by AutoConfigure().
AutoConfigure()
void AutoConfigurer::AutoConfigure (const std::string & config_file_path)
Definition at line 16 of file auto_configurer.cpp.
References AfterConfigure(), BeforeConfigure(), ConfigureConnectors(), CreateMosaicConnector(), ReadConfigs(), and ResolveConnectors().
BeforeConfigure()
virtual void mosaic::auto_configurer::AutoConfigurer::BeforeConfigure () inline virtual
Definition at line 22 of file auto_configurer.h.
Referenced by AutoConfigure().
ConfigureConnectors()
void AutoConfigurer::ConfigureConnectors ()
Definition at line 66 of file auto_configurer.cpp.
References configurable_connectors_, dc_handler_map_, mosaic_connector_, MOSAIC_LOG_ERROR, MOSAIC_LOG_INFO, and mt_handler_map_.
Referenced by AutoConfigure().
CreateMosaicConnector()
void AutoConfigurer::CreateMosaicConnector ()
Definition at line 32 of file auto_configurer.cpp.
References mosaic_config_, and mosaic_connector_.
Referenced by AutoConfigure().
GetMosaicConnector()
std::shared_ptr< core::MosaicConnector > mosaic::auto_configurer::AutoConfigurer::GetMosaicConnector () const inline
Definition at line 28 of file auto_configurer.h.
References mosaic_connector_.
ReadConfigs()
void AutoConfigurer::ReadConfigs (const std::string & config_file_path)
Definition at line 25 of file auto_configurer.cpp.
References config_reader_, mosaic::auto_configurer::ConfigReaderResolver::GetConfigReader(), mosaic::auto_configurer::ConfigReaderResolver::GetInstance(), and mosaic_config_.
Referenced by AutoConfigure().
ResolveConnectors()
void AutoConfigurer::ResolveConnectors ()
Definition at line 39 of file auto_configurer.cpp.
References configurable_connectors_, mosaic::auto_configurer::ConnectorResolver::GetInstance(), mosaic_config_, and MOSAIC_LOG_ERROR.
Referenced by AutoConfigure().
Member Data Documentation
config_reader_
std::shared_ptr<IConfigReader> mosaic::auto_configurer::AutoConfigurer::config_reader_ private
Definition at line 48 of file auto_configurer.h.
Referenced by ReadConfigs().
configurable_connectors_
std::vector<std::shared_ptr<IConfigurableConnector> > mosaic::auto_configurer::AutoConfigurer::configurable_connectors_ protected
Definition at line 43 of file auto_configurer.h.
Referenced by ConfigureConnectors(), and ResolveConnectors().
dc_handler_map_
std::unordered_map<std::string, std::shared_ptr<handlers::IDataChannelHandler> > mosaic::auto_configurer::AutoConfigurer::dc_handler_map_ protected
Definition at line 44 of file auto_configurer.h.
Referenced by ConfigureConnectors().
mosaic_config_
std::shared_ptr<core::MosaicConfig> mosaic::auto_configurer::AutoConfigurer::mosaic_config_ protected
Definition at line 41 of file auto_configurer.h.
Referenced by CreateMosaicConnector(), ReadConfigs(), and ResolveConnectors().
mosaic_connector_
std::shared_ptr<core::MosaicConnector> mosaic::auto_configurer::AutoConfigurer::mosaic_connector_ protected
Definition at line 42 of file auto_configurer.h.
Referenced by ConfigureConnectors(), CreateMosaicConnector(), and GetMosaicConnector().
mt_handler_map_
std::unordered_map<std::string, std::shared_ptr<handlers::IMediaTrackHandler> > mosaic::auto_configurer::AutoConfigurer::mt_handler_map_ protected
Definition at line 45 of file auto_configurer.h.
Referenced by ConfigureConnectors().
The documentation for this class was generated from the following files:
include/mosaic/auto_configurer/auto_configurer.h
src/auto_configurer/auto_configurer.cpp