MOSAIC RTC Core: mosaic::core_log::ILogger Class Reference
mosaic::core_log::ILogger Class Reference abstract
#include <i_logger.h>
Public Member Functions
virtual ~ILogger ()=default
virtual void LOG (const std::string &message, LogLevel log_level)=0
void LOG_DEBUG (const std::string &message)
template<typename... Args>
void LOG_DEBUG (const std::string &format, Args &&... args)
void LOG_WARNING (const std::string &message)
template<typename... Args>
void LOG_WARNING (const std::string &format, Args &&... args)
void LOG_INFO (const std::string &message)
template<typename... Args>
void LOG_INFO (const std::string &format, Args &&... args)
void LOG_ERROR (const std::string &message)
template<typename... Args>
void LOG_ERROR (const std::string &format, Args &&... args)
Static Public Member Functions
static LogLevel GetLogLevel ()
static bool IsDebugEnabled ()
static bool IsInfoEnabled ()
static bool IsWarningEnabled ()
static bool IsErrorEnabled ()
Detailed Description
Definition at line 17 of file i_logger.h.
Constructor & Destructor Documentation
~ILogger()
virtual mosaic::core_log::ILogger::~ILogger () virtual default
Member Function Documentation
GetLogLevel()
static LogLevel mosaic::core_log::ILogger::GetLogLevel () inline static
Definition at line 83 of file i_logger.h.
References mosaic::core_log::LogService::GetInstance(), and mosaic::core_log::LogService::GetLogLevel().
IsDebugEnabled()
static bool mosaic::core_log::ILogger::IsDebugEnabled () inline static
Definition at line 87 of file i_logger.h.
References mosaic::core_log::DEBUG, mosaic::core_log::LogService::GetInstance(), and mosaic::core_log::LogService::GetLogLevel().
Referenced by LOG_DEBUG(), and LOG_DEBUG().
IsErrorEnabled()
static bool mosaic::core_log::ILogger::IsErrorEnabled () inline static
Definition at line 99 of file i_logger.h.
References mosaic::core_log::ERROR, mosaic::core_log::LogService::GetInstance(), and mosaic::core_log::LogService::GetLogLevel().
Referenced by LOG_ERROR(), and LOG_ERROR().
IsInfoEnabled()
static bool mosaic::core_log::ILogger::IsInfoEnabled () inline static
Definition at line 91 of file i_logger.h.
References mosaic::core_log::LogService::GetInstance(), mosaic::core_log::LogService::GetLogLevel(), and mosaic::core_log::INFO.
Referenced by LOG_INFO(), and LOG_INFO().
IsWarningEnabled()
static bool mosaic::core_log::ILogger::IsWarningEnabled () inline static
Definition at line 95 of file i_logger.h.
References mosaic::core_log::LogService::GetInstance(), mosaic::core_log::LogService::GetLogLevel(), and mosaic::core_log::WARNING.
Referenced by LOG_WARNING(), and LOG_WARNING().
LOG()
virtual void mosaic::core_log::ILogger::LOG (const std::string & message, LogLevel log_level) pure virtual
Implemented in mosaic::core_log::ConsoleLogger.
Referenced by LOG_DEBUG(), LOG_DEBUG(), LOG_ERROR(), LOG_ERROR(), LOG_INFO(), LOG_INFO(), LOG_WARNING(), and LOG_WARNING().
LOG_DEBUG() [1/2]
template<typename... Args> void mosaic::core_log::ILogger::LOG_DEBUG (const std::string & format, Args &&... args) inline
Definition at line 30 of file i_logger.h.
References mosaic::core_log::DEBUG, IsDebugEnabled(), and LOG().
LOG_DEBUG() [2/2]
void mosaic::core_log::ILogger::LOG_DEBUG (const std::string & message) inline
Definition at line 23 of file i_logger.h.
References mosaic::core_log::DEBUG, IsDebugEnabled(), and LOG().
LOG_ERROR() [1/2]
template<typename... Args> void mosaic::core_log::ILogger::LOG_ERROR (const std::string & format, Args &&... args) inline
Definition at line 75 of file i_logger.h.
References mosaic::core_log::ERROR, IsErrorEnabled(), and LOG().
LOG_ERROR() [2/2]
void mosaic::core_log::ILogger::LOG_ERROR (const std::string & message) inline
Definition at line 68 of file i_logger.h.
References mosaic::core_log::ERROR, IsErrorEnabled(), and LOG().
LOG_INFO() [1/2]
template<typename... Args> void mosaic::core_log::ILogger::LOG_INFO (const std::string & format, Args &&... args) inline
Definition at line 60 of file i_logger.h.
References mosaic::core_log::INFO, IsInfoEnabled(), and LOG().
LOG_INFO() [2/2]
void mosaic::core_log::ILogger::LOG_INFO (const std::string & message) inline
Definition at line 53 of file i_logger.h.
References mosaic::core_log::INFO, IsInfoEnabled(), and LOG().
LOG_WARNING() [1/2]
template<typename... Args> void mosaic::core_log::ILogger::LOG_WARNING (const std::string & format, Args &&... args) inline
Definition at line 45 of file i_logger.h.
References IsWarningEnabled(), LOG(), and mosaic::core_log::WARNING.
LOG_WARNING() [2/2]
void mosaic::core_log::ILogger::LOG_WARNING (const std::string & message) inline
Definition at line 38 of file i_logger.h.
References IsWarningEnabled(), LOG(), and mosaic::core_log::WARNING.
The documentation for this class was generated from the following file:
include/mosaic/logger/i_logger.h