MOSAIC RTC Core: mosaic::core::ConnectorStateManager Class Reference
mosaic::core::ConnectorStateManager Class Reference final
#include <connector_state_manager.h>
Public Types
enum State {
INITIALIZING , READY_TO_CONNECT , RTC_CONNECTING , RTC_CONNECTED ,
RTC_DISCONNECTING , RTC_FAILED , DISCONNECTED
}
Public Member Functions
ConnectorStateManager (const std::shared_ptr< core_signaling::ISignalingClient > &signaling_client)
void SetState (State new_state)
State GetState () const
std::string GetStateString () const
bool IsState (State expected_state) const
Static Public Member Functions
static std::string StateToString (State state)
static int StateToInt (State state)
Private Member Functions
void SendState () const
Static Private Member Functions
static void LogState (State old_state, State new_state)
Private Attributes
State state_
std::shared_ptr< core_signaling::ISignalingClient > signaling_client_
std::shared_mutex mutex_
Detailed Description
Definition at line 15 of file connector_state_manager.h.
Member Enumeration Documentation
State
enum mosaic::core::ConnectorStateManager::State
Enumerator
INITIALIZING
READY_TO_CONNECT
RTC_CONNECTING
RTC_CONNECTED
RTC_DISCONNECTING
RTC_FAILED
DISCONNECTED
Definition at line 17 of file connector_state_manager.h.
Constructor & Destructor Documentation
ConnectorStateManager()
ConnectorStateManager::ConnectorStateManager (const std::shared_ptr< core_signaling::ISignalingClient > & signaling_client) explicit
Definition at line 12 of file connector_state_manager.cpp.
Member Function Documentation
GetState()
ConnectorStateManager::State ConnectorStateManager::GetState () const
Definition at line 22 of file connector_state_manager.cpp.
References mutex_, and state_.
GetStateString()
std::string ConnectorStateManager::GetStateString () const
Definition at line 27 of file connector_state_manager.cpp.
References mutex_, state_, and StateToString().
IsState()
bool ConnectorStateManager::IsState (State expected_state) const
Definition at line 32 of file connector_state_manager.cpp.
References mutex_, and state_.
LogState()
void ConnectorStateManager::LogState (State old_state, State new_state) static private
Definition at line 45 of file connector_state_manager.cpp.
References MOSAIC_LOG_INFO, and StateToString().
Referenced by SetState().
SendState()
void ConnectorStateManager::SendState () const private
Definition at line 37 of file connector_state_manager.cpp.
References MOSAIC_LOG_ERROR, signaling_client_, state_, and StateToInt().
Referenced by SetState().
SetState()
void ConnectorStateManager::SetState (State new_state)
Definition at line 15 of file connector_state_manager.cpp.
References LogState(), mutex_, SendState(), and state_.
StateToInt()
int ConnectorStateManager::StateToInt (State state) static
Definition at line 70 of file connector_state_manager.cpp.
References DISCONNECTED, INITIALIZING, READY_TO_CONNECT, RTC_CONNECTED, RTC_CONNECTING, RTC_DISCONNECTING, and RTC_FAILED.
Referenced by SendState().
StateToString()
std::string ConnectorStateManager::StateToString (State state) static
Definition at line 49 of file connector_state_manager.cpp.
References DISCONNECTED, INITIALIZING, READY_TO_CONNECT, RTC_CONNECTED, RTC_CONNECTING, RTC_DISCONNECTING, and RTC_FAILED.
Referenced by GetStateString(), and LogState().
Member Data Documentation
mutex_
std::shared_mutex mosaic::core::ConnectorStateManager::mutex_ mutable private
Definition at line 43 of file connector_state_manager.h.
Referenced by GetState(), GetStateString(), IsState(), and SetState().
signaling_client_
std::shared_ptr<core_signaling::ISignalingClient> mosaic::core::ConnectorStateManager::signaling_client_ private
Definition at line 42 of file connector_state_manager.h.
Referenced by SendState().
state_
State mosaic::core::ConnectorStateManager::state_ private
Definition at line 41 of file connector_state_manager.h.
Referenced by GetState(), GetStateString(), IsState(), SendState(), and SetState().
The documentation for this class was generated from the following files:
include/mosaic/core/connector_state_manager.h
src/core/connector_state_manager.cpp