MOSAIC RTC Core: mosaic::auto_configurer::YamlConfigReader::Impl Class Reference
mosaic::auto_configurer::YamlConfigReader::Impl Class Reference
Public Member Functions
Impl ()=default
YAML::Node LoadFile (const std::string &file_path)
MosaicConfig ParseConnectorConfigs (const YAML::Node &node)
ConnectorConfig ParseConnectorConfig (const YAML::Node &node)
ServerConfig ParseServerConfig (const YAML::Node &node)
AuthConfig ParseAuthConfig (const YAML::Node &node)
WebRtcConfig ParseWebRtcConfig (const YAML::Node &node)
std::vector< IceServerConfig > ParseIceServers (const YAML::Node &node)
Detailed Description
Definition at line 11 of file yaml_config_reader.cpp.
Constructor & Destructor Documentation
Impl()
mosaic::auto_configurer::YamlConfigReader::Impl::Impl () default
Member Function Documentation
LoadFile()
YAML::Node mosaic::auto_configurer::YamlConfigReader::Impl::LoadFile (const std::string & file_path) inline
Definition at line 15 of file yaml_config_reader.cpp.
ParseAuthConfig()
AuthConfig mosaic::auto_configurer::YamlConfigReader::Impl::ParseAuthConfig (const YAML::Node & node) inline
Definition at line 87 of file yaml_config_reader.cpp.
References mosaic::core::AuthConfig::params, mosaic::core::AuthConfig::robot_id, and mosaic::core::AuthConfig::type.
Referenced by mosaic::auto_configurer::YamlConfigReader::Impl::ParseServerConfig().
ParseConnectorConfig()
ConnectorConfig mosaic::auto_configurer::YamlConfigReader::Impl::ParseConnectorConfig (const YAML::Node & node) inline
Definition at line 39 of file yaml_config_reader.cpp.
References mosaic::core::ConnectorConfig::label, mosaic::core::ConnectorConfig::params, and mosaic::core::ConnectorConfig::type.
Referenced by mosaic::auto_configurer::YamlConfigReader::Impl::ParseConnectorConfigs().
ParseConnectorConfigs()
MosaicConfig mosaic::auto_configurer::YamlConfigReader::Impl::ParseConnectorConfigs (const YAML::Node & node) inline
Definition at line 19 of file yaml_config_reader.cpp.
References mosaic::core::MosaicConfig::connectors, mosaic::auto_configurer::YamlConfigReader::Impl::ParseConnectorConfig(), mosaic::auto_configurer::YamlConfigReader::Impl::ParseServerConfig(), and mosaic::core::MosaicConfig::server.
ParseIceServers()
std::vector< IceServerConfig > mosaic::auto_configurer::YamlConfigReader::Impl::ParseIceServers (const YAML::Node & node) inline
Definition at line 123 of file yaml_config_reader.cpp.
References mosaic::core::IceServerConfig::credential, mosaic::core::IceServerConfig::urls, and mosaic::core::IceServerConfig::username.
Referenced by mosaic::auto_configurer::YamlConfigReader::Impl::ParseWebRtcConfig().
ParseServerConfig()
ServerConfig mosaic::auto_configurer::YamlConfigReader::Impl::ParseServerConfig (const YAML::Node & node) inline
Definition at line 63 of file yaml_config_reader.cpp.
References mosaic::core::ServerConfig::auth_config, mosaic::auto_configurer::YamlConfigReader::Impl::ParseAuthConfig(), mosaic::auto_configurer::YamlConfigReader::Impl::ParseWebRtcConfig(), mosaic::core::ServerConfig::webrtc_config, and mosaic::core::ServerConfig::ws_url.
Referenced by mosaic::auto_configurer::YamlConfigReader::Impl::ParseConnectorConfigs().
ParseWebRtcConfig()
WebRtcConfig mosaic::auto_configurer::YamlConfigReader::Impl::ParseWebRtcConfig (const YAML::Node & node) inline
Definition at line 111 of file yaml_config_reader.cpp.
References mosaic::core::WebRtcConfig::ice_servers, and mosaic::auto_configurer::YamlConfigReader::Impl::ParseIceServers().
Referenced by mosaic::auto_configurer::YamlConfigReader::Impl::ParseServerConfig().
The documentation for this class was generated from the following file:
src/config_reader/yaml_config_reader.cpp