MOSAIC RTC Core: mosaic::handlers::DataChannelReceivable< ReceiveT > Class Template Reference
mosaic::handlers::DataChannelReceivable< ReceiveT > Class Template Reference abstract
#include <data_channel_receivable.h>
Public Member Functions
DataChannelReceivable (const std::string &label)
~DataChannelReceivable () override=default
void OnMessage (const webrtc::DataBuffer &buffer) override
Public Member Functions inherited from mosaic::handlers::IDataChannelReceivable
IDataChannelReceivable (const std::string &label)
~IDataChannelReceivable () override=default
Public Member Functions inherited from mosaic::handlers::ADataChannelHandler
ADataChannelHandler (const std::string &label)
~ADataChannelHandler () override=default
std::string GetLabel () const override
void SetDataChannelInterface (const webrtc::scoped_refptr< webrtc::DataChannelInterface > &dc_interface) const override
void RegisterDataChannelObserver () const override
ChannelState GetState () const override
void CloseDataChannel () const override
Public Member Functions inherited from mosaic::handlers::IDataChannelHandler
IDataChannelHandler ()=default
virtual ~IDataChannelHandler ()=default
virtual void AfterCreate ()
Protected Member Functions
virtual ReceiveT ConvertBufferToData (const webrtc::DataBuffer &buffer)=0
virtual void HandleData (const ReceiveT &)
Additional Inherited Members
Public Types inherited from mosaic::handlers::IDataChannelHandler
enum ChannelState {
kConnecting , kOpen , kClosing , kClosed ,
kUnknown
}
Detailed Description
template<typename ReceiveT>
class mosaic::handlers::DataChannelReceivable< ReceiveT >
Definition at line 26 of file data_channel_receivable.h.
Constructor & Destructor Documentation
DataChannelReceivable()
template<typename ReceiveT > mosaic::handlers::DataChannelReceivable< ReceiveT >::DataChannelReceivable (const std::string & label) inline explicit
Definition at line 28 of file data_channel_receivable.h.
~DataChannelReceivable()
template<typename ReceiveT > mosaic::handlers::DataChannelReceivable< ReceiveT >::~DataChannelReceivable () override default
Member Function Documentation
ConvertBufferToData()
template<typename ReceiveT > virtual ReceiveT mosaic::handlers::DataChannelReceivable< ReceiveT >::ConvertBufferToData (const webrtc::DataBuffer & buffer) protected pure virtual
Referenced by mosaic::handlers::DataChannelReceivable< ReceiveT >::OnMessage().
HandleData()
template<typename ReceiveT > virtual void mosaic::handlers::DataChannelReceivable< ReceiveT >::HandleData (const ReceiveT &) inline protected virtual
Definition at line 44 of file data_channel_receivable.h.
Referenced by mosaic::handlers::DataChannelReceivable< ReceiveT >::OnMessage().
OnMessage()
template<typename ReceiveT > void mosaic::handlers::DataChannelReceivable< ReceiveT >::OnMessage (const webrtc::DataBuffer & buffer) inline override virtual
Implements mosaic::handlers::IDataChannelReceivable.
Definition at line 32 of file data_channel_receivable.h.
References mosaic::handlers::DataChannelReceivable< ReceiveT >::ConvertBufferToData(), mosaic::handlers::DataChannelReceivable< ReceiveT >::HandleData(), and MOSAIC_LOG_ERROR.
The documentation for this class was generated from the following file:
include/mosaic/handlers/data_channel/data_channel_receivable.h