MOSAIC RTC Core: mosaic::auto_configurer::ConfigReaderResolver Class Reference
mosaic::auto_configurer::ConfigReaderResolver Class Reference
#include <config_reader_resolver.h>
Public Member Functions
bool IsSupportedFile (const std::string &file_path)
std::shared_ptr< IConfigReader > GetConfigReader (const std::string &file_path)
template<typename T >
void RegisterConfigReader ()
void RegisterConfigReader (const std::shared_ptr< IConfigReaderFactory > &factory)
ConfigReaderResolver (const ConfigReaderResolver &)=delete
ConfigReaderResolver & operator= (const ConfigReaderResolver &)=delete
Static Public Member Functions
static ConfigReaderResolver & GetInstance ()
Private Member Functions
ConfigReaderResolver ()
Private Attributes
std::vector< std::shared_ptr< IConfigReaderFactory > > factories_
Detailed Description
Definition at line 15 of file config_reader_resolver.h.
Constructor & Destructor Documentation
ConfigReaderResolver() [1/2]
mosaic::auto_configurer::ConfigReaderResolver::ConfigReaderResolver (const ConfigReaderResolver &) delete
ConfigReaderResolver() [2/2]
ConfigReaderResolver::ConfigReaderResolver () private
Definition at line 67 of file config_reader_resolver.cpp.
References factories_.
Member Function Documentation
GetConfigReader()
std::shared_ptr< IConfigReader > ConfigReaderResolver::GetConfigReader (const std::string & file_path)
Definition at line 51 of file config_reader_resolver.cpp.
References ExtractFileExtension(), and factories_.
Referenced by mosaic::auto_configurer::AutoConfigurer::ReadConfigs().
GetInstance()
ConfigReaderResolver & ConfigReaderResolver::GetInstance () static
Definition at line 14 of file config_reader_resolver.cpp.
Referenced by mosaic::auto_configurer::AutoConfigurer::ReadConfigs().
IsSupportedFile()
bool ConfigReaderResolver::IsSupportedFile (const std::string & file_path)
Definition at line 35 of file config_reader_resolver.cpp.
References ExtractFileExtension(), and factories_.
operator=()
ConfigReaderResolver & mosaic::auto_configurer::ConfigReaderResolver::operator= (const ConfigReaderResolver &) delete
RegisterConfigReader() [1/2]
template<typename T > void mosaic::auto_configurer::ConfigReaderResolver::RegisterConfigReader () inline
Definition at line 24 of file config_reader_resolver.h.
References factories_.
RegisterConfigReader() [2/2]
void mosaic::auto_configurer::ConfigReaderResolver::RegisterConfigReader (const std::shared_ptr< IConfigReaderFactory > & factory) inline
Definition at line 30 of file config_reader_resolver.h.
References factories_.
Member Data Documentation
factories_
std::vector<std::shared_ptr<IConfigReaderFactory> > mosaic::auto_configurer::ConfigReaderResolver::factories_ private
Definition at line 39 of file config_reader_resolver.h.
Referenced by ConfigReaderResolver(), GetConfigReader(), IsSupportedFile(), RegisterConfigReader(), and RegisterConfigReader().
The documentation for this class was generated from the following files:
include/mosaic/auto_configurer/config_reader/config_reader_resolver.h
src/config_reader/config_reader_resolver.cpp