MOSAIC RTC Core: mosaic::core_signaling::WebSocketClient Class Reference
mosaic::core_signaling::WebSocketClient Class Reference
#include <websocket_client.h>
Public Types
using OnConnectedCallback = std::function< void()>
using OnDisconnectedCallback = std::function< void()>
using OnMessageCallback = std::function< void(const std::string &)>
using OnErrorCallback = std::function< void(const std::string &)>
Public Member Functions
WebSocketClient ()
~WebSocketClient ()
void setOnConnected (OnConnectedCallback callback)
void setOnDisconnected (OnDisconnectedCallback callback)
void setOnMessage (OnMessageCallback callback)
void setOnError (OnErrorCallback callback)
void connect (const std::string &uri)
void disconnect ()
void send (const std::string &message) const
void sendJson (const Json::Value &jsonMessage) const
bool isConnected () const
Private Member Functions
void connectInternal ()
void handleMessage (const websocket_incoming_message &message) const
void handleClose (websocket_close_status close_status, const std::string &reason, const std::error_code &)
void setupEventHandlers ()
Private Attributes
std::shared_ptr< websocket_callback_client > m_client = nullptr
std::atomic< bool > m_connected
std::string m_uri
OnConnectedCallback m_onConnected
OnDisconnectedCallback m_onDisconnected
OnMessageCallback m_onMessage
OnErrorCallback m_onError
Detailed Description
Definition at line 21 of file websocket_client.h.
Member Typedef Documentation
OnConnectedCallback
using mosaic::core_signaling::WebSocketClient::OnConnectedCallback = std::function<void()>
Definition at line 24 of file websocket_client.h.
OnDisconnectedCallback
using mosaic::core_signaling::WebSocketClient::OnDisconnectedCallback = std::function<void()>
Definition at line 25 of file websocket_client.h.
OnErrorCallback
using mosaic::core_signaling::WebSocketClient::OnErrorCallback = std::function<void(const std::string&)>
Definition at line 27 of file websocket_client.h.
OnMessageCallback
using mosaic::core_signaling::WebSocketClient::OnMessageCallback = std::function<void(const std::string&)>
Definition at line 26 of file websocket_client.h.
Constructor & Destructor Documentation
WebSocketClient()
WebSocketClient::WebSocketClient ()
Definition at line 14 of file websocket_client.cpp.
~WebSocketClient()
WebSocketClient::~WebSocketClient ()
Definition at line 16 of file websocket_client.cpp.
References disconnect(), and m_connected.
Member Function Documentation
connect()
void WebSocketClient::connect (const std::string & uri)
Definition at line 38 of file websocket_client.cpp.
References connectInternal(), m_connected, and m_uri.
connectInternal()
void WebSocketClient::connectInternal () private
Definition at line 45 of file websocket_client.cpp.
References m_client, m_connected, m_onConnected, m_uri, MOSAIC_LOG_ERROR, MOSAIC_LOG_INFO, and setupEventHandlers().
Referenced by connect(), and handleClose().
disconnect()
void WebSocketClient::disconnect ()
Definition at line 80 of file websocket_client.cpp.
References m_client, m_connected, m_onDisconnected, MOSAIC_LOG_ERROR, and MOSAIC_LOG_INFO.
Referenced by ~WebSocketClient().
handleClose()
void WebSocketClient::handleClose (websocket_close_status close_status, const std::string & reason, const std::error_code &) private
Definition at line 175 of file websocket_client.cpp.
References connectInternal(), m_connected, m_onDisconnected, MOSAIC_LOG_ERROR, and MOSAIC_LOG_INFO.
Referenced by setupEventHandlers().
handleMessage()
void WebSocketClient::handleMessage (const websocket_incoming_message & message) const private
Definition at line 137 of file websocket_client.cpp.
References m_client, m_onError, m_onMessage, and MOSAIC_LOG_DEBUG.
Referenced by setupEventHandlers().
isConnected()
bool WebSocketClient::isConnected () const
Definition at line 123 of file websocket_client.cpp.
References m_connected.
send()
void WebSocketClient::send (const std::string & message) const
Definition at line 101 of file websocket_client.cpp.
References m_client, m_connected, and MOSAIC_LOG_ERROR.
Referenced by sendJson().
sendJson()
void WebSocketClient::sendJson (const Json::Value & jsonMessage) const
Definition at line 116 of file websocket_client.cpp.
References send().
setOnConnected()
void WebSocketClient::setOnConnected (OnConnectedCallback callback)
Definition at line 22 of file websocket_client.cpp.
References m_onConnected.
setOnDisconnected()
void WebSocketClient::setOnDisconnected (OnDisconnectedCallback callback)
Definition at line 26 of file websocket_client.cpp.
References m_onDisconnected.
setOnError()
void WebSocketClient::setOnError (OnErrorCallback callback)
Definition at line 34 of file websocket_client.cpp.
References m_onError.
setOnMessage()
void WebSocketClient::setOnMessage (OnMessageCallback callback)
Definition at line 30 of file websocket_client.cpp.
References m_onMessage.
setupEventHandlers()
void WebSocketClient::setupEventHandlers () private
Definition at line 127 of file websocket_client.cpp.
References handleClose(), handleMessage(), and m_client.
Referenced by connectInternal().
Member Data Documentation
m_client
std::shared_ptr<websocket_callback_client> mosaic::core_signaling::WebSocketClient::m_client = nullptr private
Definition at line 52 of file websocket_client.h.
Referenced by connectInternal(), disconnect(), handleMessage(), send(), and setupEventHandlers().
m_connected
std::atomic<bool> mosaic::core_signaling::WebSocketClient::m_connected private
Definition at line 53 of file websocket_client.h.
Referenced by connect(), connectInternal(), disconnect(), handleClose(), isConnected(), send(), and ~WebSocketClient().
m_onConnected
OnConnectedCallback mosaic::core_signaling::WebSocketClient::m_onConnected private
Definition at line 56 of file websocket_client.h.
Referenced by connectInternal(), and setOnConnected().
m_onDisconnected
OnDisconnectedCallback mosaic::core_signaling::WebSocketClient::m_onDisconnected private
Definition at line 57 of file websocket_client.h.
Referenced by disconnect(), handleClose(), and setOnDisconnected().
m_onError
OnErrorCallback mosaic::core_signaling::WebSocketClient::m_onError private
Definition at line 59 of file websocket_client.h.
Referenced by handleMessage(), and setOnError().
m_onMessage
OnMessageCallback mosaic::core_signaling::WebSocketClient::m_onMessage private
Definition at line 58 of file websocket_client.h.
Referenced by handleMessage(), and setOnMessage().
m_uri
std::string mosaic::core_signaling::WebSocketClient::m_uri private
Definition at line 54 of file websocket_client.h.
Referenced by connect(), and connectInternal().
The documentation for this class was generated from the following files:
include/mosaic/signaling/websocket_client.h
src/signaling/websocket_client.cpp