MOSAIC RTC Core: mosaic::handlers::AMediaTrackHandler Class Reference
mosaic::handlers::AMediaTrackHandler Class Reference abstract
#include <a_media_track_handler.h>
Classes
class Impl
Public Member Functions
AMediaTrackHandler (const std::string &track_name, bool recordable)
~AMediaTrackHandler () override
virtual void Start ()=0
virtual void Stop ()=0
void SendFrame (const webrtc::VideoFrame &frame)
void SendFrame (const cv::Mat &frame, std::chrono::steady_clock::time_point start_time)
bool IsRunning () const
webrtc::scoped_refptr< webrtc::VideoTrackSourceInterface > CreateVideoTrackSource () override
void Close () override
Public Member Functions inherited from mosaic::handlers::IMediaTrackHandler
IMediaTrackHandler (std::string track_name)
virtual ~IMediaTrackHandler ()=default
std::string GetTrackName () const
Public Member Functions inherited from mosaic::handlers::Recordable
Recordable (bool recordable)
virtual ~Recordable ()
void SetRecordFilePath (const std::string &record_file_path)
void SetVideoParameters (double fps, int width, int height)
void StartRecording ()
void PauseRecording ()
void ResumeRecording ()
void StopRecording ()
void RecordFrame (const cv::Mat &frame)
Protected Member Functions
void SetRunning (bool running) const
bool GetStopFlag () const
void SetStopFlag (bool stop_flag) const
Private Attributes
std::unique_ptr< Impl > pImpl
Additional Inherited Members
Protected Attributes inherited from mosaic::handlers::IMediaTrackHandler
std::string track_name_
Detailed Description
Definition at line 18 of file a_media_track_handler.h.
Constructor & Destructor Documentation
AMediaTrackHandler()
AMediaTrackHandler::AMediaTrackHandler (const std::string & track_name, bool recordable) explicit
Definition at line 161 of file a_media_track_handler.cpp.
References pImpl.
~AMediaTrackHandler()
AMediaTrackHandler::~AMediaTrackHandler () override
Definition at line 166 of file a_media_track_handler.cpp.
References Close().
Member Function Documentation
Close()
void AMediaTrackHandler::Close () override virtual
Implements mosaic::handlers::IMediaTrackHandler.
Definition at line 190 of file a_media_track_handler.cpp.
References pImpl, Stop(), and mosaic::handlers::Recordable::StopRecording().
Referenced by ~AMediaTrackHandler().
CreateVideoTrackSource()
webrtc::scoped_refptr< webrtc::VideoTrackSourceInterface > AMediaTrackHandler::CreateVideoTrackSource () override virtual
Implements mosaic::handlers::IMediaTrackHandler.
Definition at line 184 of file a_media_track_handler.cpp.
References pImpl, and Start().
GetStopFlag()
bool AMediaTrackHandler::GetStopFlag () const protected
Definition at line 200 of file a_media_track_handler.cpp.
References pImpl.
IsRunning()
bool AMediaTrackHandler::IsRunning () const
Definition at line 180 of file a_media_track_handler.cpp.
References pImpl.
SendFrame() [1/2]
void AMediaTrackHandler::SendFrame (const cv::Mat & frame, std::chrono::steady_clock::time_point start_time)
Definition at line 175 of file a_media_track_handler.cpp.
References pImpl, and mosaic::handlers::Recordable::RecordFrame().
SendFrame() [2/2]
void AMediaTrackHandler::SendFrame (const webrtc::VideoFrame & frame)
Definition at line 170 of file a_media_track_handler.cpp.
References pImpl, mosaic::handlers::Recordable::RecordFrame(), and mosaic::handlers::AMediaTrackHandler::Impl::VideoFrame2CvMat().
SetRunning()
void AMediaTrackHandler::SetRunning (bool running) const protected
Definition at line 196 of file a_media_track_handler.cpp.
References pImpl.
SetStopFlag()
void AMediaTrackHandler::SetStopFlag (bool stop_flag) const protected
Definition at line 204 of file a_media_track_handler.cpp.
References pImpl.
Start()
virtual void mosaic::handlers::AMediaTrackHandler::Start () pure virtual
Referenced by CreateVideoTrackSource().
Stop()
virtual void mosaic::handlers::AMediaTrackHandler::Stop () pure virtual
Referenced by Close().
Member Data Documentation
pImpl
std::unique_ptr<Impl> mosaic::handlers::AMediaTrackHandler::pImpl private
Definition at line 47 of file a_media_track_handler.h.
Referenced by AMediaTrackHandler(), Close(), CreateVideoTrackSource(), GetStopFlag(), IsRunning(), SendFrame(), SendFrame(), SetRunning(), and SetStopFlag().
The documentation for this class was generated from the following files:
include/mosaic/handlers/media_track/a_media_track_handler.h
src/handlers/media_track/a_media_track_handler.cpp