MOSAIC RTC Core: mosaic::core_log::LogService Class Reference
mosaic::core_log::LogService Class Reference
#include <log_service.h>
Public Member Functions
LogService (const LogService &)=delete
LogService & operator= (const LogService &)=delete
LogLevel GetLogLevel () const
Static Public Member Functions
static LogService & GetInstance ()
Public Attributes
LogLevel log_level_ = INFO
std::shared_ptr< ILogger > logger_ = DefaultLogger()
Private Member Functions
LogService ()=default
~LogService ()=default
Static Private Member Functions
static std::shared_ptr< ILogger > DefaultLogger ()
Detailed Description
Definition at line 16 of file log_service.h.
Constructor & Destructor Documentation
LogService() [1/2]
mosaic::core_log::LogService::LogService (const LogService &) delete
LogService() [2/2]
mosaic::core_log::LogService::LogService () private default
~LogService()
mosaic::core_log::LogService::~LogService () private default
Member Function Documentation
DefaultLogger()
std::shared_ptr< ILogger > LogService::DefaultLogger () static private
Definition at line 10 of file log_service.cpp.
GetInstance()
static LogService & mosaic::core_log::LogService::GetInstance () inline static
Definition at line 18 of file log_service.h.
Referenced by mosaic::core_log::GetLogger(), mosaic::core_log::ILogger::GetLogLevel(), mosaic::core_log::GetLogLevel(), mosaic::core_log::ILogger::IsDebugEnabled(), mosaic::core_log::ILogger::IsErrorEnabled(), mosaic::core_log::ILogger::IsInfoEnabled(), mosaic::core_log::ILogger::IsWarningEnabled(), mosaic::core_log::RegisterLogger(), and mosaic::core_log::SetLogLevel().
GetLogLevel()
LogLevel mosaic::core_log::LogService::GetLogLevel () const inline
Definition at line 27 of file log_service.h.
References log_level_.
Referenced by mosaic::core_log::ILogger::GetLogLevel(), mosaic::core_log::ILogger::IsDebugEnabled(), mosaic::core_log::ILogger::IsErrorEnabled(), mosaic::core_log::ILogger::IsInfoEnabled(), and mosaic::core_log::ILogger::IsWarningEnabled().
operator=()
LogService & mosaic::core_log::LogService::operator= (const LogService &) delete
Member Data Documentation
log_level_
LogLevel mosaic::core_log::LogService::log_level_ = INFO
Definition at line 31 of file log_service.h.
Referenced by mosaic::core_log::GetLogLevel(), GetLogLevel(), and mosaic::core_log::SetLogLevel().
logger_
std::shared_ptr<ILogger> mosaic::core_log::LogService::logger_ = DefaultLogger()
Definition at line 32 of file log_service.h.
Referenced by mosaic::core_log::GetLogger(), and mosaic::core_log::RegisterLogger().
The documentation for this class was generated from the following files:
include/mosaic/logger/log_service.h
src/logger/log_service.cpp