MOSAIC RTC Core: mosaic::core_log Namespace Reference
mosaic::core_log Namespace Reference
Classes
class ConsoleLogger
class ILogger
class LogService
Enumerations
enum LogLevel { DEBUG = 0 , WARNING = 1 , INFO = 2 , ERROR = 3 }
enum WebRTCLogLevel {
LS_VERBOSE , LS_INFO , LS_WARNING , LS_ERROR ,
LS_NONE
}
Functions
template<typename Impl , typename... Args>
void RegisterLogger (Args &&... args)
std::shared_ptr< ILogger > GetLogger ()
void SetLogLevel (const LogLevel level)
LogLevel GetLogLevel ()
void SetWebRTCLogLevel (WebRTCLogLevel level)
void SetWebRTCLogTimestamps (bool enable)
void SetWebRTCLogThreads (bool enable)
Enumeration Type Documentation
LogLevel
enum mosaic::core_log::LogLevel
Enumerator
DEBUG
WARNING
INFO
ERROR
Definition at line 9 of file log_level.h.
WebRTCLogLevel
enum mosaic::core_log::WebRTCLogLevel
Enumerator
LS_VERBOSE
LS_INFO
LS_WARNING
LS_ERROR
LS_NONE
Definition at line 9 of file webrtc_log.h.
Function Documentation
GetLogger()
std::shared_ptr< ILogger > mosaic::core_log::GetLogger () inline
Definition at line 48 of file log_service.h.
References mosaic::core_log::LogService::GetInstance(), and mosaic::core_log::LogService::logger_.
GetLogLevel()
LogLevel mosaic::core_log::GetLogLevel () inline
Definition at line 56 of file log_service.h.
References mosaic::core_log::LogService::GetInstance(), and mosaic::core_log::LogService::log_level_.
RegisterLogger()
template<typename Impl , typename... Args> void mosaic::core_log::RegisterLogger (Args &&... args)
Definition at line 43 of file log_service.h.
References mosaic::core_log::LogService::GetInstance(), and mosaic::core_log::LogService::logger_.
SetLogLevel()
void mosaic::core_log::SetLogLevel (const LogLevel level) inline
Definition at line 52 of file log_service.h.
References mosaic::core_log::LogService::GetInstance(), and mosaic::core_log::LogService::log_level_.
SetWebRTCLogLevel()
void mosaic::core_log::SetWebRTCLogLevel (WebRTCLogLevel level)
Definition at line 8 of file webrtc_log.cpp.
References LS_ERROR, LS_INFO, LS_NONE, LS_VERBOSE, and LS_WARNING.
SetWebRTCLogThreads()
void mosaic::core_log::SetWebRTCLogThreads (bool enable = true)
Definition at line 32 of file webrtc_log.cpp.
SetWebRTCLogTimestamps()
void mosaic::core_log::SetWebRTCLogTimestamps (bool enable = true)
Definition at line 28 of file webrtc_log.cpp.