@startuml
'https://plantuml.com/class-diagram

class RobotWebRTCClient {
    - robot_id: String
    - user_id: String
    - peer_connection_manager: PeerConnectionManager
    - state_manager: ClientStateManager
    - data_channel_handlers_dict: Dict<String, ADataChannelHandler>
    - media_track_handlers_dict: Dict<String, IMediaTrackHandler>

    + RobotWebRTCClient(robot_id: String, user_id: String)
}

abstract class ADataChannelHandler {
    - label: String
    - need_to_create: Boolean
    - dc_interface: DataChannelInterface
    + observer: DataChannelObserver

    + ADataChannelHandler(label: String, need_to_create: Boolean)
    + GetLabel(): String
    + NeedToCreate(): Boolean
    + GetState(): ChannelState
    + CloseDataChannel()
    + {abstract} AfterCreate()
    + {abstract} OnMessage(buffer: DataBuffer)
    + CreateDataChannel(peer_connection: PeerConnectionInterface)
    + SetDataChannelInterface(dc_interface: DataChannelInterface)
    + RegisterDataChannelObserver()
    + RegisterDataChannelObserver(dc_handler: ADataChannelHandler)
}

enum ChannelState {
    kConnecting
    kOpen
    kClosing
    kClosed
    kUnknown
}

class DatachannelSendable extends ADataChannelHandler {
    + DatachannelSendable(label: String, need_to_create: Boolean)
    + Sendable(): Boolean
    + Send(buffer: DataBuffer)
    + SendString(string: String)
    + SendStringAsByte(string: String)
    + SendJson(json: Json)
}

abstract class IDataChannelReceivable extends ADataChannelHandler {
    + IDataChannelReceivable(label: String, need_to_create: Boolean)
    + ConvertDataBufferToJson(buffer: DataBuffer): Json
    + {abstract} OnMessage(buffer: DataBuffer)
}

abstract class DataChannelReceivable<ReceiveT> extends IDataChannelReceivable {
    + DataChannelReceivable(label: String, need_to_create: Boolean)
    + OnMessage(buffer: DataBuffer)
    + {abstract} ConvertJsonToData(json: Json): ReceiveT
    + {abstract} HandleData(data: ReceiveT)
}

' Relationships
RobotWebRTCClient "1" *-- "many" ADataChannelHandler

ChannelState -* ADataChannelHandler

@enduml