@startuml
'https://plantuml.com/class-diagram

package ba_gcs_core {
    package handler {
        class DCSendable {}
        abstract class ADCReceivable<ReceiveT> {}
        abstract class AMediaTrackHandler {}
    }
}

package ba_gcs_autoconfigurer {
    abstract AConfigurable {}

    class ConnectorRegisterer {}
}


package ba_gcs_ros2 {
    package handler {
        class ImageMediaTrackHandler extends ba_gcs_core.handler.AMediaTrackHandler {}
        class PointCloud2Sender extends ba_gcs_core.handler.DCSendable {}
        class TwistReceiver extends ba_gcs_core.handler.ADCReceivable {}
    }

    package configurer {
        class ImageMediaTrackHandlerConfigurer extends ba_gcs_autoconfigurer.AConfigurable {}
        class PointCloud2SenderConfigurer extends ba_gcs_autoconfigurer.AConfigurable {}

        class TwistReceiverConfigurer extends ba_gcs_autoconfigurer.AConfigurable {}
    }

    package ros {
        class GCSConnectorNode {}

        class GCSConnectorNodeFactory {}

        class RosLogger {}
    }

}
PointCloud2Sender <-- PointCloud2SenderConfigurer
TwistReceiver <-- TwistReceiverConfigurer
GCSConnectorNode <-- GCSConnectorNodeFactory

package ba_gcs_husky_ros2 {
    package handler {
        class HuksyStatusSender extends ba_gcs_core.handler.DCSendable {}
    }

    package configurer {
        class HuksyStatusSenderConfigurer extends ba_gcs_autoconfigurer.AConfigurable {}
    }
}

@enduml