@startuml
'https://plantuml.com/class-diagram

class RobotWebRTCClientFactory {
    - robot_id: String
    - user_id: String
    - ice_config: IceConfig
    - signaling_config: SignalingConfig
    + RobotWebRTCClient(robot_id: String, user_id: String,
                        signaling_config: SignalingConfig, ice_config: IceConfig)
    + RobotWebRTCClient(robot_id: String, user_id: String, ws_uri: String,
                        turn_url: String, turn_username: String, turn_credential: String)
    + Create(): RobotWebRTCClient
}

struct IceConfig {
    - turn_url: std::string
    - turn_username: std::string
    - turn_credential: std::string
    + IceConfig(url: String, username: String, credential: String)
}

struct SignalingConfig {
    - ws_uri: String
    - robot_id: String
    + SignalingConfig(ws_uri: String, robot_id: String)
    + GetSignalingUrl(): String
}

class SignalingServer {
    - robot_webrtc_client: RobotWebRTCClient
    - ws_client: WebSocketClient
    - is_connected: Boolean
    - ws_uri: String

    + SignalingServer(ws_uri: String)
    + SetRobotWebrtcClient(robot_webrtc_client: RobotWebRTCClient)
    + Start()
    + Stop()
    + SendSdpAnswer(sdp_answer: SessionDescription)
    + SendIceCandidate(candidate: IceCandidate)
    + SendState(state: String)

    - StartInternal()
    - OnWsMessage(message: String)
    - OnMessage(message: Json)
    - SendWsMessage(message: Json)

    - ResolveIceCandidate(ice_candidate: Json): IceCandidate
    - ResolveSdpOffer(sdp_offer: Json): SessionDescription
}

enum ClientState {
    INITIALIZING
    READY_TO_CONNECT
    CONNECTING
    CONNECTED
    DISCONNECTING
    FAILED
    SHUTTING_DOWN
}

class ClientStateManager {
    - state: ClientState
    - signaling_server: SignalingServer

    + ClientStateManager(signalingServer: SignalingServer)
    + GetState(): ClientState
    + SetState(new_state: ClientState)
    + GetStateString(): String
    + IsState(expected_state: ClientState): Boolean

    - LogState(old_state: ClientState, new_state: ClientState)
    - SendStateToSignalingServer()
    - StateToString(state: ClientState): String
}

class RobotWebRTCClient {
    - robot_id: String
    - user_id: String
    - peer_connection_manager: PeerConnectionManager
    - state_manager: ClientStateManager
    - data_channel_handlers_dict: Dict<String, ADataChannelHandler>
    - media_track_handlers_dict: Dict<String, IMediaTrackHandler>

    + RobotWebRTCClient(robot_id: String, user_id: String)
    + GetRobotId(): String
    + GetUserId(): String
    + SetPeerConnectionManager(peer_connection_manager: PeerConnectionManager)
    + StartSignalingServer()
    + InitializeWebRTC()
    + AddDataChannelHandler(handler: ADataChannelHandler)
    + AddMediaTrackHandler(handler: IMediaTrackHandler)
    + ClosePeerConnection()
    + ShuttingDown()

    + HandleSdpOffer(sdp_offer: SessionDescription)
    + HandleIceCandidateFromSignaling(candidate: IceCandidate)
    + OnDataChannel(data_channel: DataChannel)
    + GetStateManager(): ClientStateManager

    - CreateAllMediaTracks()
    - CreateAllDataChannels()
    - CloseAllMediaTracks()
    - CloseAllDataChannels()
}

class PeerConnectionManager {
    - client: RobotWebRTCClient
    - state_manager: ClientStateManager
    - ice_config: IceConfig
    - signaling_server: SignalingServer

    - peer_connection_factory: PeerConnectionFactoryInterface
    - peer_connection: PeerConnectionInterface
    - peer_connection_observer: PeerConnectionObserver

    + PeerConnectionManager(client: RobotWebRTCClient, state_manager: ClientStateManager,
                            signaling_config: SignalingConfig, ice_config: IceConfig)
    + StartSignalingServer()
    + InitializeWebRTC()
    + CreatePeerConnection()
    + HandleSdpOffer(sdp_offer: SessionDescription)
    + AfterSetSessionDescription()
    + AfterCreateSdpAnswer(desc: SessionDescription)
    + AfterSetLocalDescription(desc: SessionDescription)
    + HandleIceCandidateFromSignaling(candidate: IceCandidate)
    + OnConnectionConnected()
    + OnConnectionDisconnected()
    + SendIceCandidate(candidate: IceCandidate)
    + StopSignalingServer()
    + ClosePeerConnection()
    + DestroyPeerConnectionManager()

    - CreateVideoTrack(source: VideoTrackSourceInterface, label: String): VideoTrackInterface
    - AddTrack(track: MediaStreamTrackInterface, stream_ids: String[]): RtpSenderInterface
}

class PeerConnectionObserver {
    - robot_webrtc_client: RobotWebRTCClient
    - peer_connection_manager: PeerConnectionManager
    - is_ice_gathering_complete: Boolean
    - ice_candidates: IceCandidate[]
    + PeerConnectionObserver(robot_webrtc_client: RobotWebRTCClient,
                            peer_connection_manager: PeerConnectionManager)

    + OnDataChannel(data_channel: DataChannel)
    + OnIceCandidate(candidate: IceCandidate)
    + OnStandardizedIceConnectionChange(new_state: IceConnectionState)
    + OnIceGatheringChange(new_state: IceGatheringState)
    + OnSignalingChange(new_state: SignalingState)
    + OnConnectionChange(new_state: PeerConnectionState)
    + IsIceGatheringComplete(): Boolean
    + GetIceCandidates(): IceCandidate[]
}

abstract class ADataChannelHandler {
    - label: String
    - need_to_create: Boolean
    - dc_interface: DataChannelInterface
    + observer: DataChannelObserver

    + ADataChannelHandler(label: String, need_to_create: Boolean)
    + GetLabel(): String
    + NeedToCreate(): Boolean
    + GetState(): ChannelState
    + CloseDataChannel()
    + {abstract} AfterCreate()
    + {abstract} OnMessage(buffer: DataBuffer)
    + CreateDataChannel(peer_connection: PeerConnectionInterface)
    + SetDataChannelInterface(dc_interface: DataChannelInterface)
    + RegisterDataChannelObserver()
    + RegisterDataChannelObserver(dc_handler: ADataChannelHandler)
}

enum ChannelState {
    kConnecting
    kOpen
    kClosing
    kClosed
    kUnknown
}

class DatachannelSendable extends ADataChannelHandler {
    + DatachannelSendable(label: String, need_to_create: Boolean)
    + Sendable(): Boolean
    + Send(buffer: DataBuffer)
    + SendString(string: String)
    + SendStringAsByte(string: String)
    + SendJson(json: Json)
}

abstract class IDataChannelReceivable extends ADataChannelHandler {
    + IDataChannelReceivable(label: String, need_to_create: Boolean)
    + ConvertDataBufferToJson(buffer: DataBuffer): Json
    + {abstract} OnMessage(buffer: DataBuffer)
}

abstract class DataChannelReceivable<ReceiveT> extends IDataChannelReceivable {
    + DataChannelReceivable(label: String, need_to_create: Boolean)
    + OnMessage(buffer: DataBuffer)
    + {abstract} ConvertJsonToData(json: Json): ReceiveT
    + {abstract} HandleData(data: ReceiveT)
}

interface IMediaTrackHandler {
    # track_name: String

    + IMediaTrackHandler(track_name: String)
    + {abstract} CreateVideoTrackSource(): VideoTrackSourceInterface
    + {abstract} Close()
    + GetTrackName(): String
}

class ActualVideoTrackSource {
    + is_running: Boolean
    + stop_flag: Boolean
    + SendFrame(frame: VideoFrame)
}
webrtc_AdaptedVideoTrackSource <|-- ActualVideoTrackSource

abstract class MediaTrackHandler implements IMediaTrackHandler {
    # actual_video_track_source: ActualVideoTrackSource
    + MediaTrackHandler(track_name: String)
    + {abstract} Start()
    + {abstract} Stop()
    + SendFrame(frame: VideoFrame)
    + SendFrame(frame: cv::Mat, start_time: time_point)
    + IsRunning(): Boolean
    + CreateVideoTrackSource(): VideoTrackSourceInterface
    + Close()
    # SetRunning(running: Boolean)
    # GetStopFlag(): Boolean
    # SetStopFlag(stop_flag: Boolean)
    - CvMat2VideoFrame(frame: cv::Mat, start_time: time_point): VideoFrame
}

enum RecordState {
    NotRecording
    Recording
    Paused
}

class Recordable {
    - recordable: Boolean
    - recorder: VideoRecorder
    - record_state: RecordState

    + Recordable(recordable: Boolean)
    + SetRecordFilePath(file_path: String)
    + StartRecording()
    + PauseRecording()
    + ResumeRecording()
    + StopRecording()
    + RecordFrame(frame: cv::Mat)
}

class VideoRecorder {
    - record_file_path: String

    + VideoRecorder(record_file_path: String)
    + Start()
    + Stop()
    + SaveFrame(frame: cv::Mat)
}

' Relationships
PeerConnectionManager *- SignalingServer
PeerConnectionObserver -* PeerConnectionManager
webrtc_PeerConnectionObserver <|- PeerConnectionObserver

SignalingServer -* ClientStateManager

RobotWebRTCClient *- ClientStateManager
ClientStateManager <- ClientState

RobotWebRTCClient "1" *-- "many" ADataChannelHandler
RobotWebRTCClient "1" *-- "many" IMediaTrackHandler

ADataChannelHandler *-- ChannelState

MediaTrackHandler <- ActualVideoTrackSource
Recordable <|-- MediaTrackHandler
Recordable *-- VideoRecorder
Recordable *-- RecordState

RobotWebRTCClientFactory ->  RobotWebRTCClient
RobotWebRTCClientFactory -- IceConfig
RobotWebRTCClientFactory -- SignalingConfig

PeerConnectionManager --* RobotWebRTCClient

@enduml